.MODEL SMALL
.STACK 64
.DATA
 MENUPAGE       DB "Welcome to Victory Sphere Multi-Purpose Sports Complex!"
                DB 13, 10, " What can I help you today?"
                DB 13, 10, "1. Register."
                DB 13, 10, "2. Login."
                DB 13, 10, "3. Menu and purchases."
                DB 13, 10, "4. Exit. $"

 NEWPAGE        DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " "
                DB 13, 10, " $"

 MEMBERMENU     DB 13, 10, " "
                DB "Please select your operations."
                DB 13, 10, "1. Change Login Details."
                DB 13, 10, "2. Order and Purchases."
                DB 13, 10, "3. Exit. $"

 MEMBERPRICE    DB 13, 10, "THIS IS THE PRICE FOR OUR BOOKINGS/ACTIVITIES :)        "
                DB 13, 10, " VENUE/ACTIVITIES:                 UOM            PRICE  "
                DB 13, 10, "[1]BASKETBALL COURTS              1 HOUR           RM10  "
                DB 13, 10, "[2]BADMINTON COURTS               1 HOUR           RM8   "
                DB 13, 10, "[3]TENNIS/PICKLEBALL COURTS       1 HOUR           RM12  "
                DB 13, 10, "[4]INDOOR SOCCER FIELD            1 HOUR           RM20  "
                DB 13, 10, "[5]VOLLEYBALL FIELD               1 HOUR           RM12  "
                DB 13, 10, "[6]SWIMMING POOL                  1 HOUR           RM25  "
                DB 13, 10, "[7]GYM                            1 HOUR           RM20  "
                DB 13, 10, "[8]GROUP EXERCISE STUDIO          1 HOUR           RM15  "
                DB 13, 10, "[9]CLIMBING WALLS                 1 HOUR           RM20 $"

 NONMEMBERPRICE DB 13, 10, "THIS IS THE PRICE FOR OUR BOOKINGS/ACTIVITIES :) "
                DB 13, 10, " VENUE/ACTIVITIES:                 UOM            PRICE  "
                DB 13, 10, "[1]BASKETBALL COURTS              1 HOUR           RM20  "
                DB 13, 10, "[2]BADMINTON COURTS               1 HOUR           RM15  "
                DB 13, 10, "[3]TENNIS/PICKLEBALL COURTS       1 HOUR           RM15  "
                DB 13, 10, "[4]INDOOR SOCCER FIELD            1 HOUR           RM30  "
                DB 13, 10, "[5]VOLLEYBALL FIELD               1 HOUR           RM15  "
                DB 13, 10, "[6]SWIMMING POOL                  1 HOUR           RM30  "
                DB 13, 10, "[7]GYM                            1 HOUR           RM30  "
                DB 13, 10, "[8]GROUP EXERCISE STUDIO          1 HOUR           RM25  "
                DB 13, 10, "[9]CLIMBING WALLS                 1 HOUR           RM30 $"

 RECEIPTHEADER  DB 13, 10, "        VICTORY SPHERE SPORTS COMPLEX"
                DB 13, 10, "NO 12, JALAN 2, TAMAN BERJAYA, KUALA LUMPUR, MALAYSIA"
                DB 13, 10, "                     0128473943                       $"
 RECEIPTNAME    DB 13, 10, "CUSTOMER USERNAME: $"
 RECEIPTDATE    DB 13, 10, "TRANSACTION TIME: $"
 RECEIPTMIDDLE  DB 13, 10, "-----------------------------------------------------"
                DB 13, 10, "                  OFFICIAL RECEIPT                   "
                DB 13, 10, "-----------------------------------------------------"
                DB 13, 10, "      ORDER DETAILS      - QTY - UOM - SUBTOTAL(RM)   $"

 RECEIPTMID2    DB 13, 10, "-----------------------------------------------------"
                DB 13, 10, "                  OFFICIAL RECEIPT                   "
                DB 13, 10, "-----------------------------------------------------"
                DB 13, 10, "                  ORDER DETAILS       $"
 RDET1          DB 13, 10, "                 BASKETBALL COURT     $"
 RDET2          DB 13, 10, "                 BADMINTON COURT      $"
 RDET3          DB 13, 10, "              TENNIS/PICKLEBALL COURT $"
 RDET4          DB 13, 10, "               INDOOR SOCCER FIELD    $"
 RDET5          DB 13, 10, "                 VOLLEYBALL FIELD     $"
 RDET6          DB 13, 10, "                   SWIMMING POOL      $"
 RDET7          DB 13, 10, "                        GYM           $"
 RDET8          DB 13, 10, "                GROUP EXERCISE STUDIO $"
 RDET9          DB 13, 10, "                   CLIMBING WALLS     $"
 RECEIPTFOOTER  DB 13, 10, "-----------------------------------------------------$"
 RECEIPTFOOT2   DB 13, 10, "TOTAL :                                RM $"
 SUBTL          DB 13, 10, "SUBTOTALS:                             RM $"
 TAX            DB 13, 10, "TAX:                                   RM $"
 REGISTERDET    DB 13, 10, "     REGISTRATION FEES     $" 
 RECEIPTEND     DB 13, 10, "             THANK YOU! HAVE A NICE DAY. $"
 PAYMENTMETHOD  DB 13, 10, "PAYMENT METHODS "
                DB 13, 10, "----------------"
                DB 13, 10, "1. CASH "
                DB 13, 10, "2. CREDIT CARD "
                DB 13, 10, "3. E-WALLET $"
 CASH           DB 13, 10, "PAYMENT METHOD: CASH PAYMENT$"
 CARD           DB 13, 10, "PAYMENT METHOD: CARD PAYMENT$"
 EWALLET        DB 13, 10, "PAYMENT METHOD E-WALLET PAYMENT$"
                DB 13, 10, "PLEASE SELECT YOUR PAYMENT METHOD: "
 DISNMCHOICE    DB 13, 10, "WHICH VENUE DO YOU WANT TO BOOK?$"
 DISHOUR        DB 13, 1O, "HOW MANY HOURS DO YOU WANT TO BOOK? (MAX 8 HOURS)$"
 CBOOK          DB 13, 10, "PRESS 1 TO CONTINUE $"

 RNAME DB 10 DUP(0)
 RPSW  DB 8 DUP(0)
 INAME DB 10 DUP(0)
 IPSW  DB 8 DUP(0)
 CPSW  DB 8 DUP(0)
 SEL   DB 0
 MSEL  DB 0
 LGIN  DB 0
 PURC  DB 0
 RFEES DB 0
 FEEQ1 DB 0
 FEER1 DB 0
 FEEQ2 DB 0
 FEER2 DB 0
 RMNS1 DB ?
 RMNS2 DB ? 
 RMNST DB 0
 TAB   DB "	$"
 UOM   DB "MONTHS$"
 CDATE DB 13, 10, "CURRENT DATE: $"
 CTIME DB 13, 10, "CURRENT TIME: $"
 MSGRN DB 13, 10, "REGISTER USERNAME (10-DIGIT) : $"
 MSGRP DB 13, 10, "ENTER BIRTHDATE (DDMMYYYY)   : $"
 MSGPW DB 13, 10, "YOUR PASSWORD IS THE BIRTHDATE ENTERED. $"
 MSGIN DB 13, 10, "ENTER NAME: $"
 MSGIP DB 13, 10, "ENTER PASSWORD: $"
 MSGCP DB 13, 10, "ENTER YOUR NEW PASSWORD (8-DIGIT): $"
 IMSG  DB 13, 10, "ACCESS DENIED! PLEASE RE-ENTER.$"
 VMSG  DB 13, 10, "ACCESS GRANTED!$"
 CMSG  DB 13, 10, "PASSWORD SUCCESSFULLY CHANGED. "
       DB 13, 10, "REDIRECTING YOU TO THE MEMBER MENU. $"
 SMSG  DB 13, 10, "PLEASE INPUT YOUR SELECTION (1-4). $"
 MSMSG DB 13, 10, "PLEASE INPUT YOUR SELECTION (1-3). $"
 MSGS  DB 13, 10, 13, 10, "REGISTERED! PRESS 1 TO PROCEED TO SUBSCRIPTION DETAILS. $"
 REG   DB 13, 10, 13, 10, "HOW MANY MONTHS DO YOU WANT TO SUBSCRIBE (MIN 1 MONTH, MAX 12 MONTH) "
       DB 13, 10, "OUR MEMBERSHIP FEES IS RM10/MONTH "
       DB 13, 10, "**IF MONTHS IS LESS THAN 10, PLEASE INPUT MONTHS AS 01,02,...ETC**"
       DB 13, 10, "PLEASE ENTER MONTH OF SUBSCRIPTION: $"
 MREG  DB 13, 10, "TOTAL REGISTRATION FEES: RM $"
 MLGIN DB 13, 10, "REDIRECTING YOU TO LOG-IN $"
 MSGGR DB 13, 10, "PLEASE WAIT RECEIPT IS GENERATING..... $"
 MSGP  DB 13, 10, "PRESS 1 TO PROCEED TO PURCHASE, PRESS 0 TO EXIT.$"
 MSGST DB 13, 10, "SUBTOTAL IS: RM $"
 EMPTY DB 13, 10, "                                                                             $"
 ATTL  DB 8 DUP(0)
 SATTL DB 8
 ABOOK DB 10 DUP(0)
 COUNT DB 0
 NMBASKETBALL     DB 20
 NMBADMINTON      DB 15
 NMTENNIS         DB 15
 NMSOCCER         DB 30
 NMVOLLEYBALL     DB 15
 NMSWIMMINGPOOL   DB 30
 NMGYM            DB 30
 NMSTUDIO         DB 25
 NMCLIMBINGWALL   DB 30

 MBASKETBALL      DB 10
 MBADMINTON       DB 8
 MTENNIS          DB 12
 MSOCCER          DB 20
 MVOLLEYBALL      DB 12
 MSWIMMINGPOOL    DB 25
 MGYM             DB 20
 MSTUDIO          DB 15
 MCLIMBINGWALL    DB 20

 VENUE     DB 0 
 HUN       DB 100
 HOURS     DB 0
 SUBTOTAL  DB 0
 SUBTQ1    DB 0
 SUBTR1    DB 0
 SUBTQ2    DB 0
 SUBTR2    DB 0
 GTTLQ1    DB 0
 GTTLR1    DB 0
 GTTLQ2    DB 0
 GTTLR2    DB 0
 FTTLQ1    DB 0
 FTTLR1    DB 0
 FTTLQ2    DB 0
 FTTLR2    DB 0
 TAXQ1     DB 0
 TAXQ2     DB 0 
 TAXR1     DB 0
 TAXR2     DB 0
 TAXQ3     DB 0
 TAXR3     DB 0
 TEN       DB 10
 TTL       DB 0
 GTTL      DB 0
 GTTLT     DW 0
 BOOK      DB 0
 UOMH      DB "HOURS$"
 ARRAYSIZE DW 10
 PAYM      DB 0 
 TEMP      DB 0
 AMTAX     DB 0
 TAX_PERCENT DB 6
 FTTL      DB 0

.CODE
MAIN PROC
MOV AX, @DATA
MOV DS, AX

FRONTPAGE:
;-----OUTPUT FRONT PAGE
MOV AH, 09H
LEA DX, NEWPAGE
INT 21H
MOV AH, 09H
LEA DX, MENUPAGE
INT 21H

;-----OUTPUT SELECTION MESSAGE
MOV AH, 09H
LEA DX, SMSG
INT 21H

;-----INPUT BYTE(SELECTION)
MOV AH, 01H
INT 21H
MOV SEL, AL

;-----CMP SEL, "1"
CMP SEL, "1"
JE REGISTRATION
;-----CMP SEL, "2"
CMP SEL, "2"
JE TEMPLOGIN
;-----CMP SEL "3"
CMP SEL, "3"
JE TEMPDNONMEMBERPRICE
;-----CMP SEL "4"
CMP SEL, "4"
JE TEMPEXIT

REGISTRATION: ;--------------------------------------REGISTRATION (COMPLETED)
;---OUTPUT STRING:09H(MSGRN)
MOV AH, 09H
LEA DX, MSGRN
INT 21H
;---INPUT BYTE:01H(RNAME[SI], USING LOOP)
MOV CX, 10
MOV SI, 0
GETREGISTRATIONNAME:
MOV AH, 01H
INT 21H
MOV RNAME[SI], AL
INC SI
LOOP GETREGISTRATIONNAME
;---OUTPUT STRING:09H(MSGRP)
MOV AH, 09H
LEA DX, MSGRP
INT 21H
;---INPUT BYTE:01H(RPSW[SI], USING LOOP)
MOV CX, 8
MOV SI, 0
GETBIRTHDAY:
MOV AH, 01H
INT 21H
MOV RPSW[SI], AL
INC SI
LOOP GETBIRTHDAY

MOV AH, 09H
LEA DX, MSGPW
INT 21H

;---OUTPUT MSGS
MOV AH, 09H
LEA DX, MSGS
INT 21H

;---SELECTION
MOV AH, 01H
INT 21H
MOV LGIN, AL
CMP LGIN, "1"
JE CALCFEES

TEMPLOGIN:
 JMP LOGIN
TEMPEXIT: 
 JMP EXIT
TEMPDNONMEMBERPRICE:
 JMP DNONMEMBERPRICE

;--------------------REGISTRTION FEES CALCULATE
CALCFEES:
;--------GETMONTH
MOV AH, 09H
LEA DX, REG
INT 21H
;-----CALC FEES
MOV AH, 01H
INT 21H
MOV RMNS1, AL
MOV AH, 01H
INT 21H
MOV RMNS2, AL
SUB RMNS1, 30H
SUB RMNS2, 30H
MOV AL, RMNS1 
MUL TEN
ADD AL, RMNS2
MOV RMNST, AL;------get month
MOV AX, 0
MOV AL, RMNST
MUL TEN
MOV RFEES, AL;-----get fees
MOV AX, 0
MOV AL, RFEES
DIV TEN
MOV FEEQ1, AL
MOV FEER1, AH
MOV AX, 0
MOV AL, FEEQ1
DIV TEN
MOV FEEQ2, AL
MOV FEER2, AH
ADD FEEQ2, 30H
ADD FEER2, 30H
ADD FEER1, 30H
MOV AH, 09H
LEA DX, MREG
INT 21H
MOV AH, 02H;-------output registration fees
MOV DL, FEEQ2
INT 21H
MOV AH, 02H
MOV DL, FEER2
INT 21H
MOV AH, 02H
MOV DL, FEER1
INT 21H
MOV AH, 09H
LEA DX, MSGGR
INT 21H
;------------------------------------------GENERATE REGISTRATION RECEIPT
MOV AH, 09H
LEA DX, NEWPAGE
INT 21H
MOV AH, 09H
LEA DX, RECEIPTHEADER
INT 21H
MOV AH,09H
LEA DX, RECEIPTNAME
INT 21H
MOV CX, 10
MOV DI, 0
PRINT: 
MOV AH, 02H
MOV DL, RNAME[DI]
INT 21H
INC DI
LOOP PRINT
MOV AH, 09H
LEA DX, RECEIPTMIDDLE
INT 21H
MOV AH, 09H
LEA DX, REGISTERDET
INT 21H
ADD RMNS1, 30H
ADD RMNS2, 30H
MOV AH, 02H
MOV DL, RMNS1
INT 21H
MOV AH, 02H
MOV DL, RMNS2
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOM
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, FEEQ2
INT 21H
MOV AH, 02H
MOV DL, FEER2
INT 21H
MOV AH, 02H
MOV DL, FEER1
INT 21H
MOV AH, 09H
LEA DX, RECEIPTFOOTER
INT 21H
MOV AH, 09H
LEA DX, RECEIPTFOOT2
INT 21H
MOV AH, 02H
MOV DL, FEEQ2
INT 21H
MOV AH, 02H
MOV DL, FEER2
INT 21H
MOV AH, 02H
MOV DL, FEER1
INT 21H
MOV AH, 09H
LEA DX, RECEIPTEND
INT 21H
MOV AH,09H
LEA DX, MLGIN
INT 21H
JMP LOGIN

LOGIN: ; --------------------------------------------------LOGIN(COMPLETED)
MOV AH, 09H
LEA DX, MSGIN
INT 21H
MOV CX, 10
MOV SI, 0
GETUSERNAME:
MOV AH, 01H
INT 21H
MOV INAME[SI], AL
INC SI
LOOP GETUSERNAME
MOV AH, 09H
LEA DX, MSGIP
INT 21H
MOV CX, 8
MOV SI, 0
GETPASSWORD:
MOV AH, 01H
INT 21H
MOV IPSW[SI], AL
INC SI
LOOP GETPASSWORD

; --- VALIDATION
MOV SI, 0
MOV DI, 0
CHKN:
CMP SI, 10  ; Compare SI to 10 for RNAME length
JE CHKP
MOV AL, RNAME[SI]
CMP AL, INAME[SI]
JNE LOGIN_ERROR ; If any character is different, jump to LOGIN_ERROR
INC SI
JMP CHKN

CHKP:
CMP DI, 8  ;
JE LOGIN_SUCCESS
MOV AL, RPSW[DI]
CMP AL, IPSW[DI]
JNE LOGIN_ERROR ; If any character is different, jump to LOGIN_ERROR
INC DI
JMP CHKP

LOGIN_ERROR:
; OUTPUT STRING:09H(IMSG)
MOV AH, 09H
LEA DX, IMSG
INT 21H
JMP LOGIN

LOGIN_SUCCESS:
; OUTPUT STRING:09H(VMSG)
MOV AH, 09H
LEA DX, VMSG
INT 21H
JMP MEMBERFRONTPAGE ; Go to the member front page

DNONMEMBERPRICE: ;----------------------------------------------------------NONMEMBERMENU & PAYMENT(MENU,SELECTION DONE)
MOV AH, 09H
LEA DX, NEWPAGE
INT 21H
MOV AH, 09H
LEA DX, NONMEMBERPRICE;------display menu
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV AH, 01H
INT 21H
MOV PURC, AL
CMP PURC, "1"
JE NONMEMBERPAYMENT;

MOV SI, 0
MOV DI, 0

NONMEMBERPAYMENT:
MOV AH, 09H
LEA DX, DISNMCHOICE
INT 21H
MOV AH, 01H
INT 21H
MOV VENUE, AL;------------see which venue is choosen
CMP VENUE, "1"
JE TEMPCNMBASKETBALL
CMP VENUE, "2"
JE TEMPCNMBADMINTON
CMP VENUE, "3"
JE TEMPCNMTENNIS
CMP VENUE, "4"
JE TEMPCNMSOCCER
CMP VENUE, "5"
JE TEMPCNMVOLLEYBALL
CMP VENUE, "6"
JE TEMPCNMSWIMMINGPOOL
CMP VENUE, "7"
JE TEMPCNMGYM
CMP VENUE, "8"
JE TEMPCNMSTUDIO
CMP VENUE, "9"
JE TEMPCNMCLIMBINGWALL
CMP VENUE, "0"
JE TEMPGENERATERECEIPT

TEMP1EXIT:
JMP TEMP2EXIT
TEMP1DISNONMEMBERPRICE:
JMP NONMEMBERPAYMENT
TEMPCNMBASKETBALL:
JMP CNMBASKETBALL
TEMPCNMBADMINTON:
JMP CNMBADMINTON
TEMPCNMTENNIS:
JMP TEMP1CNMTENNIS
TEMPCNMSOCCER:
JMP TEMP1CNMSOCCER
TEMPCNMVOLLEYBALL:
JMP TEMP1CNMVOLLEYBALL
TEMPCNMSWIMMINGPOOL:
JMP TEMP1CNMSWIMMINGPOOL
TEMPCNMGYM:
JMP TEMP1CNMGYM
TEMPCNMSTUDIO:
JMP TEMP1CNMSTUDIO
TEMPCNMCLIMBINGWALL:
JMP TEMP1CNMCLIMBINGWALL
TEMPGENERATERECEIPT:
JMP TEMP1GENERATERECEIPT




CNMBASKETBALL:;-----------------------------calc price
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, NMBASKETBALL;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[0], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET1;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "1"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP2DISNONMEMBERPRICE
CMP BOOK, "0"
JE TEMP1GENERATERECEIPT

TEMP2EXIT:
JMP TEMP3EXIT
TEMP2DISNONMEMBERPRICE:
JMP TEMP1DISNONMEMBERPRICE
TEMP1CNMTENNIS:
JMP CNMTENNIS
TEMP1CNMSOCCER:
JMP TEMP2CNMSOCCER
TEMP1CNMVOLLEYBALL:
JMP TEMP2CNMVOLLEYBALL
TEMP1CNMSWIMMINGPOOL:
JMP TEMP2CNMSWIMMINGPOOL
TEMP1CNMGYM:
JMP TEMP2CNMGYM
TEMP1CNMSTUDIO:
JMP TEMP2CNMSTUDIO
TEMP1CNMCLIMBINGWALL:
JMP TEMP2CNMCLIMBINGWALL
TEMP1GENERATERECEIPT:
JMP TEMP2GENERATERECEIPT

CNMBADMINTON:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, NMBADMINTON;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[1], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET2;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "2"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP3DISNONMEMBERPRICE
CMP BOOK, "0"
JE TEMP2GENERATERECEIPT

TEMP3DISNONMEMBERPRICE:
JMP TEMP2DISNONMEMBERPRICE
TEMP3EXIT: 
JMP TEMP4EXIT
TEMP2CNMSOCCER:
JMP CNMSOCCER
TEMP2CNMVOLLEYBALL:
JMP TEMP3CNMVOLLEYBALL
TEMP2CNMSWIMMINGPOOL:
JMP TEMP3CNMSWIMMINGPOOL
TEMP2CNMGYM:
JMP TEMP3CNMGYM
TEMP2CNMSTUDIO:
JMP TEMP3CNMSTUDIO
TEMP2CNMCLIMBINGWALL:
JMP TEMP3CNMCLIMBINGWALL
TEMP2GENERATERECEIPT:
JMP TEMP3GENERATERECEIPT


CNMTENNIS:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, NMTENNIS;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[2], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET3;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "3"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP4DISNONMEMBERPRICE
CMP BOOK, "0"
JE TEMP3GENERATERECEIPT

TEMP4DISNONMEMBERPRICE:
JMP TEMP3DISNONMEMBERPRICE
TEMP4EXIT: 
JMP TEMP5EXIT
TEMP3CNMVOLLEYBALL:
JMP CNMVOLLEYBALL
TEMP3CNMSWIMMINGPOOL:
JMP TEMP4CNMSWIMMINGPOOL
TEMP3CNMGYM:
JMP TEMP4CNMGYM
TEMP3CNMSTUDIO:
JMP TEMP4CNMSTUDIO
TEMP3CNMCLIMBINGWALL:
JMP TEMP4CNMCLIMBINGWALL
TEMP3GENERATERECEIPT:
JMP TEMP4GENERATERECEIPT


CNMSOCCER:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, NMSOCCER;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[3], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET4;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "4"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP5DISNONMEMBERPRICE
CMP BOOK, "0"
JE TEMP4GENERATERECEIPT

TEMP5DISNONMEMBERPRICE:
JMP TEMP4DISNONMEMBERPRICE
TEMP5EXIT: 
JMP TEMP6EXIT
TEMP4CNMSWIMMINGPOOL:
JMP CNMSWIMMINGPOOL
TEMP4CNMGYM:
JMP TEMP5CNMGYM
TEMP4CNMSTUDIO:
JMP TEMP5CNMSTUDIO
TEMP4CNMCLIMBINGWALL:
JMP TEMP5CNMCLIMBINGWALL
TEMP4GENERATERECEIPT:
JMP TEMP5GENERATERECEIPT

CNMVOLLEYBALL:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, NMVOLLEYBALL;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[4], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET5;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "5"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP6DISNONMEMBERPRICE
CMP BOOK, "0"
JE TEMP5GENERATERECEIPT

TEMP6DISNONMEMBERPRICE:
JMP TEMP5DISNONMEMBERPRICE
TEMP6EXIT: 
JMP TEMP7EXIT
TEMP5CNMGYM:
JMP CNMGYM
TEMP5CNMSTUDIO:
JMP TEMP6CNMSTUDIO
TEMP5CNMCLIMBINGWALL:
JMP TEMP6CNMCLIMBINGWALL
TEMP5GENERATERECEIPT:
JMP TEMP6GENERATERECEIPT

CNMSWIMMINGPOOL:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, NMSWIMMINGPOOL;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[5], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET6;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "6"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP7DISNONMEMBERPRICE
CMP BOOK, "0"
JE TEMP6GENERATERECEIPT

TEMP7DISNONMEMBERPRICE:
JMP TEMP6DISNONMEMBERPRICE
TEMP7EXIT: 
JMP TEMP8EXIT
TEMP6CNMSTUDIO:
JMP CNMSTUDIO
TEMP6CNMCLIMBINGWALL:
JMP TEMP7CNMCLIMBINGWALL
TEMP6GENERATERECEIPT:
JMP TEMP7GENERATERECEIPT

CNMGYM:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, NMGYM;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[6], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET7;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "7"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP8DISNONMEMBERPRICE
CMP BOOK, "0"
JE TEMP7GENERATERECEIPT

TEMP8DISNONMEMBERPRICE:
JMP TEMP7DISNONMEMBERPRICE
TEMP8EXIT: 
JMP TEMP9EXIT
TEMP7CNMCLIMBINGWALL:
JMP CNMCLIMBINGWALL
TEMP7GENERATERECEIPT:
JMP TEMP8GENERATERECEIPT

CNMSTUDIO:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, NMSTUDIO;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[7], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET8;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "8"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP9DISNONMEMBERPRICE
CMP BOOK, "0"
JE TEMP8GENERATERECEIPT

TEMP9DISNONMEMBERPRICE:
JMP TEMP8DISNONMEMBERPRICE
TEMP9EXIT: 
JMP TEMP10EXIT
TEMP8GENERATERECEIPT:
JMP TEMP9GENERATERECEIPT

CNMCLIMBINGWALL:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, NMCLIMBINGWALL;--------------------
MUL HOURS
MOV TTL, AL
ADD AL, 30H
MOV ATTL[8], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET9;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "9"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP10DISNONMEMBERPRICE
CMP BOOK, "0"
JE TEMP9GENERATERECEIPT

TEMP10DISNONMEMBERPRICE:
JMP TEMP9DISNONMEMBERPRICE
TEMP10EXIT: 
JMP TEMP11EXIT
TEMP9GENERATERECEIPT:
JMP GENERATENMEMBERRECEIPT

GENERATENMEMBERRECEIPT:
MOV AH, 09H
LEA DX, PAYMENTMETHOD
INT 21H
MOV AH, 01H
INT 21H
MOV PAYM, AL
MOV AH, 09H
LEA DX, NEWPAGE
INT 21H
MOV AH, 09H
LEA DX, RECEIPTHEADER
INT 21H
CMP PAYM, "1"
JE PCASH
CMP PAYM, "2"
JE PCARD
CMP PAYM, "3"
JE PEWALLET
PCASH:
MOV AH, 09H
LEA DX, CASH
INT 21H
JMP CONTINUE

PCARD:
MOV AH, 09H
LEA DX, CARD
INT 21H
JMP CONTINUE

PEWALLET:
MOV AH, 09H
LEA DX, EWALLET
INT 21H
JMP CONTINUE

CONTINUE:
MOV AH, 09H
LEA DX, RECEIPTMID2
INT 21H

MOV SI, 0   
MOV DI, 0                

DISPLAYLOOP:;-------------------------display venue chosen on receipt
cmp SI, ARRAYSIZE           
jae TEMP1END                 
MOV DL, ABOOK[SI]
CMP DL, "0"
JE PEMPTY
CMP DL, "1"
JE TEMP1PBASKETBALL
CMP DL, "2"
JE TEMP1PBADMINTON
CMP DL, "3"
JE TEMP1PTENNIS
CMP DL, "4"
JE TEMP1PSOCCER
CMP DL, "5"
JE TEMP1PVOLLEYBALL
CMP DL, "6"
JE TEMP1PSWIMMINGPOOL
CMP DL, "7"
JE TEMP1PGYM
CMP DL, "8"
JE TEMP1PSTUDIO
CMP DL, "9"
JE TEMP1PCLIMBINGWALL
TEMP1END:
JMP TEMP2END 

PEMPTY:
MOV AH, 09H
LEA DX, EMPTY
INT 21H
INC SI
JMP DISPLAYLOOP


TEMPDISPLAYLOOP:
JMP DISPLAYLOOP
TEMP1PBASKETBALL:
JMP PBASKETBALL
TEMP1PBADMINTON:
JMP TEMP2PBADMINTON
TEMP1PTENNIS:
JMP TEMP2PTENNIS
TEMP1PSOCCER:
JMP TEMP1PSOCCER
TEMP1PVOLLEYBALL:
JMP TEMP2PVOLLEYBALL
TEMP1PSWIMMINGPOOL:
JMP TEMP2PSWIMMINGPOOL
TEMP1PGYM:
JMP TEMP2PGYM
TEMP1PSTUDIO:
JMP TEMP2PSTUDIO
TEMP1PCLIMBINGWALL:
JMP TEMP2PCLIMBINGWALL

PBASKETBALL:
MOV AH, 09H
LEA DX, RDET1
INT 21H
INC SI
JMP TEMP1DISPLAYLOOP


TEMP2PBADMINTON:
JMP PBADMINTON
TEMP2PSOCCER:
JMP TEMP3PSOCCER
TEMP2PTENNIS:
JMP TEMP3PTENNIS
TEMP2PVOLLEYBALL:
JMP TEMP3PVOLLEYBALL
TEMP2PSWIMMINGPOOL:
JMP TEMP3PSWIMMINGPOOL
TEMP2PGYM:
JMP TEMP3PGYM
TEMP2PSTUDIO:
JMP TEMP3PSTUDIO
TEMP2PCLIMBINGWALL:
JMP TEMP3PCLIMBINGWALL
TEMP1DISPLAYLOOP:
JMP TEMPDISPLAYLOOP

PBADMINTON:
MOV AH, 09H
LEA DX, RDET2
INT 21H
INC SI
JMP TEMP2DISPLAYLOOP

TEMP3PTENNIS:
JMP PTENNIS
TEMP3PSOCCER:
JMP TEMP4PSOCCER
TEMP3PVOLLEYBALL:
JMP TEMP4PVOLLEYBALL
TEMP3PSWIMMINGPOOL:
JMP TEMP4PSWIMMINGPOOL
TEMP3PGYM:
JMP TEMP4PGYM
TEMP3PSTUDIO:
JMP TEMP4PSTUDIO
TEMP3PCLIMBINGWALL:
JMP TEMP4PCLIMBINGWALL
TEMP2DISPLAYLOOP:
JMP TEMP1DISPLAYLOOP

PTENNIS:
MOV AH, 09H
LEA DX, RDET3
INT 21H
INC SI
MOV AX, 0
JMP TEMP3DISPLAYLOOP

TEMP4PSOCCER:
JMP PSOCCER
TEMP4PVOLLEYBALL:
JMP TEMP5PVOLLEYBALL
TEMP4PSWIMMINGPOOL:
JMP TEMP5PSWIMMINGPOOL
TEMP4PGYM:
JMP TEMP5PGYM
TEMP4PSTUDIO:
JMP TEMP5PSTUDIO
TEMP4PCLIMBINGWALL:
JMP TEMP5PCLIMBINGWALL
TEMP3DISPLAYLOOP:
JMP TEMP2DISPLAYLOOP

PSOCCER:
MOV AH, 09H
LEA DX, RDET4
INT 21H
INC SI
JMP TEMP4DISPLAYLOOP

TEMP5PVOLLEYBALL:
JMP PVOLLEYBALL
TEMP5PSWIMMINGPOOL:
JMP TEMP6PSWIMMINGPOOL
TEMP5PGYM:
JMP TEMP6PGYM
TEMP5PSTUDIO:
JMP TEMP6PSTUDIO
TEMP5PCLIMBINGWALL:
JMP TEMP6PCLIMBINGWALL
TEMP4DISPLAYLOOP:
JMP TEMP3DISPLAYLOOP


PVOLLEYBALL:
MOV AH, 09H
LEA DX, RDET5
INT 21H
INC SI
JMP TEMP5DISPLAYLOOP

TEMP6PSWIMMINGPOOL:
JMP PSWIMMINGPOOL
TEMP6PGYM:
JMP TEMP7PGYM
TEMP6PSTUDIO:
JMP TEMP7PSTUDIO
TEMP6PCLIMBINGWALL:
JMP TEMP7PCLIMBINGWALL
TEMP5DISPLAYLOOP:
JMP TEMP4DISPLAYLOOP

PSWIMMINGPOOL:
MOV AH, 09H
LEA DX, RDET6
INT 21H
INC SI
JMP TEMP6DISPLAYLOOP

TEMP7PGYM:
JMP PGYM
TEMP7PSTUDIO:
JMP TEMP8PSTUDIO
TEMP7PCLIMBINGWALL:
JMP TEMP8PCLIMBINGWALL
TEMP6DISPLAYLOOP:
JMP TEMP5DISPLAYLOOP

PGYM:
MOV AH, 09H
LEA DX, RDET7
INT 21H
INC SI
JMP TEMP7DISPLAYLOOP

TEMP8PSTUDIO:
JMP PSTUDIO
TEMP8PCLIMBINGWALL:
JMP TEMP9PCLIMBINGWALL
TEMP7DISPLAYLOOP:
JMP TEMP6DISPLAYLOOP

PSTUDIO:
MOV AH, 09H
LEA DX, RDET8
INT 21H
INC SI
JMP TEMP8DISPLAYLOOP

TEMP9PCLIMBINGWALL:
JMP PCLIMBINGWALL
TEMP8DISPLAYLOOP:
JMP TEMP7DISPLAYLOOP

PCLIMBINGWALL:
MOV AH, 09H
LEA DX, RDET9
INT 21H
INC SI
JMP TEMP8DISPLAYLOOP

TEMP9DISPLAYLOOP:
JMP TEMP8DISPLAYLOOP

          
TEMP2END:
JMP SUM

SUM:;--------------------calc total
MOV AH, 0
MOV AL, [ATTL + 0]
ADD AH, AL
MOV AL, [ATTL + 1]
ADD AH, AL
MOV AL, [ATTL + 2]
ADD AH, AL
MOV AL, [ATTL + 3]
ADD AH, AL
MOV AL, [ATTL + 4]
ADD AH, AL
MOV AL, [ATTL + 5]
ADD AH, AL
MOV AL, [ATTL + 6]
ADD AH, AL
MOV AL, [ATTL + 7]
ADD AH, AL
MOV AL, [ATTL + 8]
ADD AH, AL
SUB AH, 8
MOV GTTL, AH
JMP CALCTAX

CALCTAX:;--------------------calc tax
MOV AL, GTTL
MOV AH, 0    
MOV BL, 6   
MUL BL       
ADD AL, 30H
MOV AMTAX, AL
JMP CALCTOTAL

CALCTOTAL:;--------------------calc final total
MOV AL, GTTL
ADD AL, AMTAX
MOV FTTL, AL
JMP ENDDISPLAY

ENDDISPLAY:;---------------------display reciept(continued)
MOV AH, 09H
LEA DX, RECEIPTFOOTER
INT 21H
MOV AH, 09H
LEA DX, SUBTL
INT 21H
MOV AX, 0
MOV AL, GTTL
DIV TEN
MOV GTTLQ1, AL
MOV GTTLR1, AH
MOV AX, 0
MOV AL, GTTLQ1
DIV TEN
MOV GTTLQ2, AL
MOV GTTLR2, AH
ADD GTTLQ2, 30H
ADD GTTLR1, 30H
ADD GTTLR2, 30H
MOV AH, 02H
MOV DL, GTTLQ2
INT 21H
MOV AH, 02H
MOV DL, GTTLR2
INT 21H
MOV AH, 02H
MOV DL, GTTLR1
INT 21H
MOV AX, 0
MOV AL, AMTAX;
DIV HUN
MOV TAXQ1, AL
MOV TAXR1, AH
MOV AX, 0
MOV AL, TAXQ1
DIV TEN
MOV TAXQ2, AL
MOV TAXR2, AH
MOV AX, 0
MOV AL, TAXR1
DIV TEN
MOV TAXQ3, AL
MOV TAXR3, AH
ADD TAXQ2,30H
ADD TAXR2,30H
ADD TAXQ3,30H
ADD TAXR3,30H
MOV AH, 09H
LEA DX, TAX
INT 21H
MOV AH, 02H
MOV DL, TAXQ2
INT 21H
MOV AH, 02H
MOV DL, TAXR2
INT 21H
;-OUTPUT BYTE:02H(.)
MOV AH, 02H  
MOV DL,'.'
INT 21H 
;-OUTPUT BYTE:02H(Q3)
MOV AH,02H
MOV DL, TAXQ3
INT 21H
;-OUTPUT BYTE:02H(R3)
MOV AH,02H
MOV DL,TAXR3
INT 21H
MOV AH, 09H
LEA DX, RECEIPTFOOT2
INT 21H
MOV AX, 0
MOV AL, FTTL
DIV TEN
MOV FTTLQ1, AL
MOV FTTLR1, AH
MOV AX, 0
MOV AL, FTTLQ1
DIV TEN
MOV FTTLQ2, AL
MOV FTTLR2, AH
ADD FTTLQ2, 30H
ADD FTTLR1, 30H
ADD FTTLR2, 30H
MOV AH, 02H
MOV DL, FTTLQ2
INT 21H
MOV AH, 02H
MOV DL, FTTLR2
INT 21H
MOV AH, 02H
MOV DL, FTTLR1
INT 21H
MOV AH, 09H
LEA DX, RECEIPTEND
INT 21H
JMP EXIT


TEMP11EXIT:
JMP EXIT

EXIT:
MOV AH, 4CH
INT 21H


MEMBERFRONTPAGE:;----------------------output member menu
MOV AH, 09H
LEA DX, NEWPAGE
INT 21H
MOV AH, 09H
LEA DX, MEMBERMENU
INT 21H
MOV AH, 01H
INT 21H
MOV MSEL, AL

CMP MSEL, "1"
JE CHANGEDETAILS
CMP MSEL, "2"
JE DMEMBERPRICE
CMP MSEL, "3"
JE EXIT
JMP MEMBERFRONTPAGE

DMEMBERPRICE:;-----------------display member pricelist
MOV AH, 09H
LEA DX, NEWPAGE
INT 21H
MOV AH, 09H
LEA DX, MEMBERPRICE
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV AH, 01H
INT 21H
MOV PURC, AL
CMP PURC, "1"
JE MEMBERPAYMENT

CHANGEDETAILS:;------------------chng password
;---OUTPUT STRING:09H(MSGCP)
MOV AH, 09H
LEA DX, MSGCP
INT 21H
;---INPUT BYTE:01H(CPSW[SI], USING LOOP)
MOV CX, 8
MOV SI, 0
GETNEWPASSWORD:
MOV AH, 01H
INT 21H
MOV CPSW[SI], AL
INC SI
LOOP GETNEWPASSWORD
;--- Output a message indicating the password change
MOV AH, 09H
LEA DX, CMSG
INT 21H;-------ADD SELECTION2
JMP MEMBERFRONTPAGE ; Go back to the member front page



MEMBERPAYMENT:;-------------------------------choose venue for member
MOV SI, 0
MOV AH, 09H
LEA DX, DISNMCHOICE
INT 21H
MOV AH, 01H
INT 21H
MOV VENUE, AL
CMP VENUE, "1"
JE TEMPCMBASKETBALL
CMP VENUE, "2"
JE TEMPCMBADMINTON
CMP VENUE, "3"
JE TEMPCMTENNIS
CMP VENUE, "4"
JE TEMPCMSOCCER
CMP VENUE, "5"
JE TEMPCMVOLLEYBALL
CMP VENUE, "6"
JE TEMPCMSWIMMINGPOOL
CMP VENUE, "7"
JE TEMPCMGYM
CMP VENUE, "8"
JE TEMPCMSTUDIO
CMP VENUE, "9"
JE TEMPCMCLIMBINGWALL
CMP VENUE, "0"
JE TEMPGENERATERECEIPTM

TEMP12EXIT:
JMP EXIT
TEMP1DISMEMBERPRICE:
JMP MEMBERPAYMENT
TEMPCMBASKETBALL:
JMP CMBASKETBALL
TEMPCMBADMINTON:
JMP CMBADMINTON
TEMPCMTENNIS:
JMP TEMP1CMTENNIS
TEMPCMSOCCER:
JMP TEMP1CMSOCCER
TEMPCMVOLLEYBALL:
JMP TEMP1CMVOLLEYBALL
TEMPCMSWIMMINGPOOL:
JMP TEMP1CMSWIMMINGPOOL
TEMPCMGYM:
JMP TEMP1CMGYM
TEMPCMSTUDIO:
JMP TEMP1CMSTUDIO
TEMPCMCLIMBINGWALL:
JMP TEMP1CMCLIMBINGWALL
TEMPGENERATERECEIPTM:
JMP TEMP1GENERATERECEIPTM



;--------------------------------------calc price
CMBASKETBALL:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, MBASKETBALL;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[0], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET1;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "1"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP2DISMEMBERPRICE
CMP BOOK, "0"
JE TEMP1GENERATERECEIPTM

TEMP13EXIT:
JMP TEMP12EXIT
TEMP2DISMEMBERPRICE:
JMP TEMP1DISMEMBERPRICE
TEMP1CMTENNIS:
JMP CMTENNIS
TEMP1CMSOCCER:
JMP TEMP2CMSOCCER
TEMP1CMVOLLEYBALL:
JMP TEMP2CMVOLLEYBALL
TEMP1CMSWIMMINGPOOL:
JMP TEMP2CMSWIMMINGPOOL
TEMP1CMGYM:
JMP TEMP2CMGYM
TEMP1CMSTUDIO:
JMP TEMP2CMSTUDIO
TEMP1CMCLIMBINGWALL:
JMP TEMP2CMCLIMBINGWALL
TEMP1GENERATERECEIPTM:
JMP TEMP2GENERATERECEIPTM

CMBADMINTON:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, MBADMINTON;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[1], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET2;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "2"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP3DISMEMBERPRICE
CMP BOOK, "0"
JE TEMP2GENERATERECEIPTM

TEMP3DISMEMBERPRICE:
JMP TEMP2DISMEMBERPRICE
TEMP14EXIT:
JMP TEMP13EXIT
TEMP2CMSOCCER:
JMP CMSOCCER
TEMP2CMVOLLEYBALL:
JMP TEMP3CMVOLLEYBALL
TEMP2CMSWIMMINGPOOL:
JMP TEMP3CMSWIMMINGPOOL
TEMP2CMGYM:
JMP TEMP3CMGYM
TEMP2CMSTUDIO:
JMP TEMP3CMSTUDIO
TEMP2CMCLIMBINGWALL:
JMP TEMP3CMCLIMBINGWALL
TEMP2GENERATERECEIPTM:
JMP TEMP3GENERATERECEIPTM


CMTENNIS:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, MTENNIS;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[2], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET3;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "3"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP4DISMEMBERPRICE
CMP BOOK, "0"
JE TEMP3GENERATERECEIPTM

TEMP4DISMEMBERPRICE:
JMP TEMP3DISMEMBERPRICE
TEMP15EXIT:
JMP TEMP14EXIT
TEMP3CMVOLLEYBALL:
JMP CMVOLLEYBALL
TEMP3CMSWIMMINGPOOL:
JMP TEMP4CMSWIMMINGPOOL
TEMP3CMGYM:
JMP TEMP4CMGYM
TEMP3CMSTUDIO:
JMP TEMP4CMSTUDIO
TEMP3CMCLIMBINGWALL:
JMP TEMP4CMCLIMBINGWALL
TEMP3GENERATERECEIPTM:
JMP TEMP4GENERATERECEIPTM


CMSOCCER:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, MSOCCER;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[3], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET4;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "4"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP5DISMEMBERPRICE
CMP BOOK, "0"
JE TEMP4GENERATERECEIPTM

TEMP5DISMEMBERPRICE:
JMP TEMP4DISMEMBERPRICE
TEMP16EXIT:
JMP TEMP15EXIT
TEMP4CMSWIMMINGPOOL:
JMP CMSWIMMINGPOOL
TEMP4CMGYM:
JMP TEMP5CMGYM
TEMP4CMSTUDIO:
JMP TEMP5CMSTUDIO
TEMP4CMCLIMBINGWALL:
JMP TEMP5CMCLIMBINGWALL
TEMP4GENERATERECEIPTM:
JMP TEMP5GENERATERECEIPTM

CMVOLLEYBALL:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, MVOLLEYBALL;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[4], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET5;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "5"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP6DISMEMBERPRICE
CMP BOOK, "0"
JE TEMP5GENERATERECEIPTM

TEMP6DISMEMBERPRICE:
JMP TEMP5DISMEMBERPRICE
TEMP17EXIT:
JMP TEMP16EXIT
TEMP5CMGYM:
JMP CMGYM
TEMP5CMSTUDIO:
JMP TEMP6CMSTUDIO
TEMP5CMCLIMBINGWALL:
JMP TEMP6CMCLIMBINGWALL
TEMP5GENERATERECEIPTM:
JMP TEMP6GENERATERECEIPTM

CMSWIMMINGPOOL:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, MSWIMMINGPOOL;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[5], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET6;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "6"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP7DISMEMBERPRICE
CMP BOOK, "0"
JE TEMP6GENERATERECEIPTM

TEMP7DISMEMBERPRICE:
JMP TEMP6DISMEMBERPRICE
TEMP18EXIT:
JMP TEMP17EXIT
TEMP6CMSTUDIO:
JMP CMSTUDIO
TEMP6CMCLIMBINGWALL:
JMP TEMP7CMCLIMBINGWALL
TEMP6GENERATERECEIPTM:
JMP TEMP7GENERATERECEIPTM

CMGYM:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, MGYM;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[6], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET7;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "7"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP8DISMEMBERPRICE
CMP BOOK, "0"
JE TEMP7GENERATERECEIPTM

TEMP8DISMEMBERPRICE:
JMP TEMP7DISMEMBERPRICE
TEMP19EXIT:
JMP TEMP18EXIT
TEMP7CMCLIMBINGWALL:
JMP CMCLIMBINGWALL
TEMP7GENERATERECEIPTM:
JMP TEMP8GENERATERECEIPTM

CMSTUDIO:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, MSTUDIO;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[7], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET8;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "8"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP9DISMEMBERPRICE
CMP BOOK, "0"
JE TEMP8GENERATERECEIPTM

TEMP9DISMEMBERPRICE:
JMP TEMP8DISMEMBERPRICE
TEMP20EXIT:
JMP TEMP19EXIT
TEMP8GENERATERECEIPTM:
JMP TEMP9GENERATERECEIPTM

CMCLIMBINGWALL:
MOV AH, 09H
LEA DX, DISHOUR
INT 21H
MOV AH, 01H
INT 21H
MOV HOURS, AL
MOV AX, 0
SUB HOURS, 30H
MOV AL, MCLIMBINGWALL;--------------------
MUL HOURS
MOV TTL, AL
MOV ATTL[8], AL
MOV AX, 0
MOV AL, TTL
DIV TEN
MOV SUBTQ1, AL
MOV SUBTR1, AH
MOV AX, 0
MOV AL, SUBTQ1
DIV TEN
MOV SUBTQ2, AL
MOV SUBTR2, AH
ADD SUBTQ2, 30H
ADD SUBTR1, 30H
ADD SUBTR2, 30H
; -----------------------RECEIPT FORMAT
MOV AH, 09H
LEA DX, RDET9;----------------
INT 21H
MOV AH, 02H
MOV DL, HOURS
ADD DL, 30H  
INT 21H
MOV BL, DL
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 09H
LEA DX, UOMH
INT 21H
MOV AH, 09H
LEA DX, TAB
INT 21H
MOV AH, 02H
MOV DL, SUBTQ2
INT 21H
MOV AH, 02H
MOV DL, SUBTR2
INT 21H
MOV AH, 02H
MOV DL, SUBTR1
INT 21H
MOV AH, 09H
LEA DX, MSGP
INT 21H
MOV ABOOK[SI], "9"
INC SI

MOV AH, 01H
INT 21H
MOV BOOK, AL
CMP BOOK, "1"
JE TEMP10DISMEMBERPRICE
CMP BOOK, "0"
JE TEMP9GENERATERECEIPTM

TEMP10DISMEMBERPRICE:
JMP TEMP9DISMEMBERPRICE
TEMP21EXIT:
JMP TEMP20EXIT
TEMP9GENERATERECEIPTM:
JMP GENERATEMEMBERRECEIPTM

GENERATEMEMBERRECEIPTM:;----------------------generate member receipt
MOV AH, 09H
LEA DX, PAYMENTMETHOD
INT 21H
MOV AH, 01H
INT 21H
MOV PAYM, AL
MOV AH, 09H
LEA DX, NEWPAGE
INT 21H
MOV AH, 09H
LEA DX, RECEIPTHEADER
INT 21H
MOV AH,09H
LEA DX, RECEIPTNAME
INT 21H
MOV CX, 10
MOV DI, 0
PRINTM: 
MOV AH, 02H
MOV DL, RNAME[DI]
INT 21H
INC DI
LOOP PRINTM
;------------------display payment method
CMP PAYM, "1"
JE MPCASH
CMP PAYM, "2"
JE MPCARD
CMP PAYM, "3"
JE MPEWALLET

MPCASH:
MOV AH, 09H
LEA DX, CASH
INT 21H
JMP CONTINUE

MPCARD:
MOV AH, 09H
LEA DX, CARD
INT 21H
JMP CONTINUE

MPEWALLET:
MOV AH, 09H
LEA DX, EWALLET
INT 21H
JMP CONTINUE

MCONTINUE:
MOV AH, 09H
LEA DX, RECEIPTMID2
INT 21H

MOV SI, 0                   

DISPLAYLOOPM:;-------------------display venue selected
cmp SI, ARRAYSIZE           
jae TEMP1ENDM                 
MOV DL, ABOOK[SI]
CMP DL, "0"
JE PEMPTYM
CMP DL, "1"
JE TEMP1PBASKETBALLM
CMP DL, "2"
JE TEMP1PBADMINTONM
CMP DL, "3"
JE TEMP1PTENNISM
CMP DL, "4"
JE TEMP1PSOCCERM
CMP DL, "5"
JE TEMP1PVOLLEYBALLM
CMP DL, "6"
JE TEMP1PSWIMMINGPOOLM
CMP DL, "7"
JE TEMP1PGYMM
CMP DL, "8"
JE TEMP1PSTUDIOM
CMP DL, "9"
JE TEMP1PCLIMBINGWALLM
TEMP1ENDM:
JMP TEMP2ENDM

PEMPTYM:
MOV AH, 09H
LEA DX, EMPTY
INT 21H
INC SI
JMP DISPLAYLOOPM


TEMPDISPLAYLOOPM:
JMP DISPLAYLOOPM
TEMP1PBASKETBALLM:
JMP PBASKETBALLM
TEMP1PBADMINTONM:
JMP TEMP2PBADMINTONM
TEMP1PTENNISM:
JMP TEMP2PTENNISM
TEMP1PSOCCERM:
JMP TEMP1PSOCCERM
TEMP1PVOLLEYBALLM:
JMP TEMP2PVOLLEYBALLM
TEMP1PSWIMMINGPOOLM:
JMP TEMP2PSWIMMINGPOOLM
TEMP1PGYMM:
JMP TEMP2PGYMM
TEMP1PSTUDIOM:
JMP TEMP2PSTUDIOM
TEMP1PCLIMBINGWALLM:
JMP TEMP2PCLIMBINGWALLM

PBASKETBALLM:
MOV AH, 09H
LEA DX, RDET1
INT 21H
INC SI
JMP TEMP1DISPLAYLOOPM


TEMP2PBADMINTONM:
JMP PBADMINTONM
TEMP2PSOCCERM:
JMP TEMP3PSOCCERM
TEMP2PTENNISM:
JMP TEMP3PTENNISM
TEMP2PVOLLEYBALLM:
JMP TEMP3PVOLLEYBALLM
TEMP2PSWIMMINGPOOLM:
JMP TEMP3PSWIMMINGPOOLM
TEMP2PGYMM:
JMP TEMP3PGYMM
TEMP2PSTUDIOM:
JMP TEMP3PSTUDIOM
TEMP2PCLIMBINGWALLM:
JMP TEMP3PCLIMBINGWALLM
TEMP1DISPLAYLOOPM:
JMP TEMPDISPLAYLOOPM

PBADMINTONM:
MOV AH, 09H
LEA DX, RDET2
INT 21H
INC SI
JMP TEMP2DISPLAYLOOPM

TEMP3PTENNISM:
JMP PTENNISM
TEMP3PSOCCERM:
JMP TEMP4PSOCCERM
TEMP3PVOLLEYBALLM:
JMP TEMP4PVOLLEYBALLM
TEMP3PSWIMMINGPOOLM:
JMP TEMP4PSWIMMINGPOOLM
TEMP3PGYMM:
JMP TEMP4PGYMM
TEMP3PSTUDIOM:
JMP TEMP4PSTUDIOM
TEMP3PCLIMBINGWALLM:
JMP TEMP4PCLIMBINGWALLM
TEMP2DISPLAYLOOPM:
JMP TEMP1DISPLAYLOOPM

PTENNISM:
MOV AH, 09H
LEA DX, RDET3
INT 21H
INC SI
MOV AX, 0
JMP TEMP3DISPLAYLOOPM

TEMP4PSOCCERM:
JMP PSOCCERM
TEMP4PVOLLEYBALLM:
JMP TEMP5PVOLLEYBALLM
TEMP4PSWIMMINGPOOLM:
JMP TEMP5PSWIMMINGPOOLM
TEMP4PGYMM:
JMP TEMP5PGYMM
TEMP4PSTUDIOM:
JMP TEMP5PSTUDIOM
TEMP4PCLIMBINGWALLM:
JMP TEMP5PCLIMBINGWALLM
TEMP3DISPLAYLOOPM:
JMP TEMP2DISPLAYLOOPM

PSOCCERM:
MOV AH, 09H
LEA DX, RDET4
INT 21H
INC SI
JMP TEMP4DISPLAYLOOPM

TEMP5PVOLLEYBALLM:
JMP PVOLLEYBALLM
TEMP5PSWIMMINGPOOLM:
JMP TEMP6PSWIMMINGPOOLM
TEMP5PGYMM:
JMP TEMP6PGYMM
TEMP5PSTUDIOM:
JMP TEMP6PSTUDIOM
TEMP5PCLIMBINGWALLM:
JMP TEMP6PCLIMBINGWALLM
TEMP4DISPLAYLOOPM:
JMP TEMP3DISPLAYLOOPM


PVOLLEYBALLM:
MOV AH, 09H
LEA DX, RDET5
INT 21H
INC SI
JMP TEMP5DISPLAYLOOPM

TEMP6PSWIMMINGPOOLM:
JMP PSWIMMINGPOOLM
TEMP6PGYMM:
JMP TEMP7PGYMM
TEMP6PSTUDIOM:
JMP TEMP7PSTUDIOM
TEMP6PCLIMBINGWALLM:
JMP TEMP7PCLIMBINGWALLM
TEMP5DISPLAYLOOPM:
JMP TEMP4DISPLAYLOOPM

PSWIMMINGPOOLM:
MOV AH, 09H
LEA DX, RDET6
INT 21H
INC SI
JMP TEMP6DISPLAYLOOPM

TEMP7PGYMM:
JMP PGYMM
TEMP7PSTUDIOM:
JMP TEMP8PSTUDIOM
TEMP7PCLIMBINGWALLM:
JMP TEMP8PCLIMBINGWALLM
TEMP6DISPLAYLOOPM:
JMP TEMP5DISPLAYLOOPM

PGYMM:
MOV AH, 09H
LEA DX, RDET7
INT 21H
INC SI
JMP TEMP7DISPLAYLOOPM

TEMP8PSTUDIOM:
JMP PSTUDIOM
TEMP8PCLIMBINGWALLM:
JMP TEMP9PCLIMBINGWALLM
TEMP7DISPLAYLOOPM:
JMP TEMP6DISPLAYLOOPM

PSTUDIOM:
MOV AH, 09H
LEA DX, RDET8
INT 21H
INC SI
JMP TEMP8DISPLAYLOOPM

TEMP9PCLIMBINGWALLM:
JMP PCLIMBINGWALLM
TEMP8DISPLAYLOOPM:
JMP TEMP7DISPLAYLOOPM

PCLIMBINGWALLM:
MOV AH, 09H
LEA DX, RDET9
INT 21H
INC SI
JMP TEMP8DISPLAYLOOPM

TEMP9DISPLAYLOOPM:
JMP TEMP8DISPLAYLOOPM

          
TEMP2ENDM:
JMP MSUM

MSUM:;--------------------calc subtotal
MOV AH, 0
MOV AL, [ATTL + 0]
ADD AH, AL
MOV AL, [ATTL + 1]
ADD AH, AL
MOV AL, [ATTL + 2]
ADD AH, AL
MOV AL, [ATTL + 3]
ADD AH, AL
MOV AL, [ATTL + 4]
ADD AH, AL
MOV AL, [ATTL + 5]
ADD AH, AL
MOV AL, [ATTL + 6]
ADD AH, AL
MOV AL, [ATTL + 7]
ADD AH, AL
MOV AL, [ATTL + 8]
ADD AH, AL
MOV GTTL, AH
JMP MCALCTAX

MCALCTAX:;-----------------------calctax
MOV AL, 0    
MOV BL, 0   
MUL BL       
MOV AMTAX, 0
JMP CALCTOTAL

MCALCTOTAL:;---------------------calctotal
MOV AL, GTTL
ADD AL, AMTAX
MOV FTTL, AL
JMP ENDDISPLAY

MENDDISPLAY:;------------------------display reciept
MOV AH, 09H
LEA DX, RECEIPTFOOTER
INT 21H
MOV AH, 09H
LEA DX, SUBTL
INT 21H
MOV AX, 0
MOV AL, GTTL
DIV TEN
MOV GTTLQ1, AL
MOV GTTLR1, AH
MOV AX, 0
MOV AL, GTTLQ1
DIV TEN
MOV GTTLQ2, AL
MOV GTTLR2, AH
ADD GTTLQ2, 30H
ADD GTTLR1, 30H
ADD GTTLR2, 30H
MOV AH, 02H
MOV DL, GTTLQ2
INT 21H
MOV AH, 02H
MOV DL, GTTLR2
INT 21H
MOV AH, 02H
MOV DL, GTTLR1
INT 21H
MOV AX, 0
MOV AL, AMTAX;
DIV HUN
MOV TAXQ1, AL
MOV TAXR1, AH
MOV AX, 0
MOV AL, TAXQ1
DIV TEN
MOV TAXQ2, AL
MOV TAXR2, AH
MOV AX, 0
MOV AL, TAXR1
DIV TEN
MOV TAXQ3, AL
MOV TAXR3, AH
ADD TAXQ2,30H
ADD TAXR2,30H
ADD TAXQ3,30H
ADD TAXR3,30H
MOV AH, 09H
LEA DX, TAX
INT 21H
MOV AH, 02H
MOV DL, TAXQ2
INT 21H
MOV AH, 02H
MOV DL, TAXR2
INT 21H
;-OUTPUT BYTE:02H(.)
MOV AH, 02H  
MOV DL,'.'
INT 21H 
;-OUTPUT BYTE:02H(Q3)
MOV AH,02H
MOV DL, TAXQ3
INT 21H
;-OUTPUT BYTE:02H(R3)
MOV AH,02H
MOV DL,TAXR3
INT 21H
MOV AH, 09H
LEA DX, RECEIPTFOOT2
INT 21H
MOV AX, 0
MOV AL, FTTL
DIV TEN
MOV FTTLQ1, AL
MOV FTTLR1, AH
MOV AX, 0
MOV AL, FTTLQ1
DIV TEN
MOV FTTLQ2, AL
MOV FTTLR2, AH
ADD FTTLQ2, 30H
ADD FTTLR1, 30H
ADD FTTLR2, 30H
MOV AH, 02H
MOV DL, FTTLQ2
INT 21H
MOV AH, 02H
MOV DL, FTTLR2
INT 21H
MOV AH, 02H
MOV DL, FTTLR1
INT 21H
MOV AH, 09H
LEA DX, RECEIPTEND
INT 21H
JMP EXIT

TEMP22EXIT:
JMP TEMP21EXIT

MAIN ENDP
END MAIN
